// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class Exercise
{
    public int ExerciseId { get; set; }

    public string Name { get; set; } = null!;

    public int? ImageId { get; set; }

    public bool IsActive { get; set; }

    public virtual Image? Image { get; set; }

    public virtual ICollection<Set> Sets { get; set; } = new List<Set>();

    public virtual ICollection<TemplateExercise> TemplateExercises { get; set; } = new List<TemplateExercise>();

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();
}