// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class Image
{
    public int ImageId { get; set; }

    public byte[] ContentFile { get; set; } = null!;

    public bool? IsDefaultForExercise { get; set; }

    public bool? IsDefaultForUser { get; set; }

    public virtual ICollection<Exercise> Exercises { get; set; } = new List<Exercise>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}