// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class Meal
{
    public int MealId { get; set; }

    public Guid UserId { get; set; }

    public Guid LastModifiedBy { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public DateTime Date { get; set; }

    public virtual User LastModifiedByNavigation { get; set; } = null!;

    public virtual ICollection<MealFood> MealFoods { get; set; } = new List<MealFood>();

    public virtual User User { get; set; } = null!;
}