// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class RoleApplication
{
    public int RoleApplicationId { get; set; }

    public Guid UserId { get; set; }

    public byte AppliedRoleId { get; set; }

    public bool IsPending { get; set; }

    public Guid? ApprovedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? ApprovedDate { get; set; }

    public virtual Role AppliedRole { get; set; } = null!;

    public virtual User? ApprovedByNavigation { get; set; }

    public virtual User User { get; set; } = null!;
}