// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class Set
{
    public int SetId { get; set; }

    public int WorkoutId { get; set; }

    public int ExerciseId { get; set; }

    public int Reps { get; set; }

    public int? Weight { get; set; }

    public int? Rpe { get; set; }

    public virtual Exercise Exercise { get; set; } = null!;

    public virtual Workout Workout { get; set; } = null!;
}