// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class Template
{
    public int TemplateId { get; set; }

    public Guid CreatedBy { get; set; }

    public bool? IsDefault { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid LastModifiedBy { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public string Title { get; set; } = null!;

    public bool IsActive { get; set; }

    public virtual User CreatedByNavigation { get; set; } = null!;

    public virtual User LastModifiedByNavigation { get; set; } = null!;

    public virtual ICollection<TemplateExercise> TemplateExercises { get; set; } = new List<TemplateExercise>();

    public virtual ICollection<Workout> Workouts { get; set; } = new List<Workout>();
}