// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class TemplateExercise
{
    public int TemplateId { get; set; }

    public int ExerciseId { get; set; }

    public int Sets { get; set; }

    public virtual Exercise Exercise { get; set; } = null!;

    public virtual Template Template { get; set; } = null!;
}