// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class User
{
    public Guid Id { get; set; }

    public string Email { get; set; } = null!;

    public Guid CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public Guid LastModifiedBy { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public bool IsActive { get; set; }

    public string? Password { get; set; }

    public byte RoleId { get; set; }

    public string UserName { get; set; } = null!;

    public int ImageId { get; set; }

    public virtual ICollection<Comment> CommentLastModifiedByNavigations { get; set; } = new List<Comment>();

    public virtual ICollection<Comment> CommentUsers { get; set; } = new List<Comment>();

    public virtual User CreatedByNavigation { get; set; } = null!;

    public virtual Image Image { get; set; } = null!;

    public virtual ICollection<User> InverseCreatedByNavigation { get; set; } = new List<User>();

    public virtual ICollection<Like> Likes { get; set; } = new List<Like>();

    public virtual ICollection<Log> Logs { get; set; } = new List<Log>();

    public virtual ICollection<Meal> MealLastModifiedByNavigations { get; set; } = new List<Meal>();

    public virtual ICollection<Meal> MealUsers { get; set; } = new List<Meal>();

    public virtual ICollection<Notification> NotificationCreatedByNavigations { get; set; } = new List<Notification>();

    public virtual ICollection<Notification> NotificationUsers { get; set; } = new List<Notification>();

    public virtual Role Role { get; set; } = null!;

    public virtual ICollection<RoleApplication> RoleApplicationApprovedByNavigations { get; set; } = new List<RoleApplication>();

    public virtual ICollection<RoleApplication> RoleApplicationUsers { get; set; } = new List<RoleApplication>();

    public virtual ICollection<Template> TemplateCreatedByNavigations { get; set; } = new List<Template>();

    public virtual ICollection<Template> TemplateLastModifiedByNavigations { get; set; } = new List<Template>();

    public virtual ICollection<Workout> WorkoutLastModifiedByNavigations { get; set; } = new List<Workout>();

    public virtual ICollection<Workout> WorkoutUsers { get; set; } = new List<Workout>();

    public virtual ICollection<User> FollowedUsers { get; set; } = new List<User>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}