// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class VwAvgExertion
{
    public Guid UserId { get; set; }

    public decimal? AvgOverTime { get; set; }

    public decimal? AvgLast3Weeks { get; set; }
}