// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class VwExercise
{
    public int ExerciseId { get; set; }

    public string Name { get; set; } = null!;

    public int? ImageId { get; set; }

    public bool IsActive { get; set; }

    public int CategoryId { get; set; }
}