// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class VwStatsPerWeek
{
    public Guid UserId { get; set; }

    public int? NoSets { get; set; }

    public int? TotalVolume { get; set; }

    public decimal? AvgRpe { get; set; }

    public decimal? ExertionIndex { get; set; }

    public DateOnly? FirstDayOfWeek { get; set; }
}