// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class VwStatsForTemplateProgress
{
    public int WorkoutId { get; set; }

    public int? TemplateId { get; set; }

    public DateOnly? CreatedDate { get; set; }

    public int? WorkoutVolume { get; set; }

    public decimal? IncreaseFromLastWorkout { get; set; }
}