// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class VwSuggestedAthlete
{
    public Guid Id { get; set; }

    public string Username { get; set; } = null!;

    public int NoFollowers { get; set; }
}