// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class VwTemplateExerciseExtension
{
    public int ExerciseId { get; set; }

    public int TemplateId { get; set; }

    public string Name { get; set; } = null!;
}