// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DA.Entities;

public partial class VwWorkoutsThisWeek
{
    public int WorkoutId { get; set; }

    public int? LikeCount { get; set; }

    public int? CommentCount { get; set; }


}