export default {
  ExerciseCreate: "Create an Exercise",
  Workouts: "Workouts",
  UserEdit: "Edit Profile",
  EditExercise: "Edit Exercise",
  CategorySelect: "Select categories",
  WorkoutWithNoExError: "Can&apos;t create workout without exercises",
  ImageSelect: "Select an image",
  Create: "Create",
  Remove: "Remove",
  Cancel: "Cancel",
  Edit: "Edit",
  Use: "Use",
  RemoveEntityModal: "Are you sure you want to remove the",
  TemplateAddTitle: "Enter a title for the template",
  filterByMuscle: "Filter by Muscle",
  enterTemplateTitle: "Enter a title for the template",
  CategoryCreate: "Create a category",
  CategoryUpdate: "Edit a category",
  UsedExerciseAlert: "Exercise already in log",
  WriteComment: "Write a comment...",
  EditComment: "Edit Comment",
  ShowMoreComments: "Show more comments",
  HideComments: "Hide comments",

  CoachApplications: "Athlete Applications",
  EmptyLog: "you haven`t added any exercise",
  EmptyLogTitle: "No Exercises",

  EmptyFeedTitle: "Your feed is empty",
  EmptyFeed: "Search for users to follow or explore suggested athletes to start seeing workouts in your feed",

  NoWorkoutsTitle: "You have no workouts",
  NoWorkouts: "Workouts you log in the Log Workout page will appear here",
  RPE: "Rate of perceived exertion (RPE) is used to measure how hard your body works during physical activity. It runs from 0 – 10, using numbers to rate how much effort an activity takes. The RPE scale can help you manage exercise intensity and improve cardio training and endurance.",
  FeaturedWorkoutTitle: "Featured Workout",
};
